# Test your FastAPI endpoints

### Root
GET http://127.0.0.1:8000/
Accept: application/json

### Create car
POST http://127.0.0.1:8000/cars
Content-Type: application/json

{
  "brand": "Toyota",
  "model": "Corolla",
  "year": 2020
}

### List cars
GET http://127.0.0.1:8000/cars
Accept: application/json

### Get by id
GET http://127.0.0.1:8000/cars/1
Accept: application/json

### Delete by id
DELETE http://127.0.0.1:8000/cars/1
Accept: application/json

